server:
  port: 5000

spring:
  r2dbc:
    url: r2dbc:postgresql://172.21.0.2:5432/user-domain-api
    username: postgres
    password: strong-password
    maxSize: 100

jwt:
  secret: strong-secret

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
